language: python

python:
- "2.7"
- "3.4"  

before_install:
- "which pip"
- "sudo apt-get -qq install liblapack-dev python-numpy python-scipy python-sklearn pip" # gfortran
- "which pip"
- "pip -V"
- "which python"
- "pip show scipy"
- "pip install coverage nose"
- "pip install 'six>=1.10.0'"
- "pip install numpy"
- "pip install 'scikit-learn>=0.10.0'"
- "pip install matplotlib"
- "pip install 'scipy>=0.9.0'"
- "pip install 'Keras==1.0.3'"
- "pip install 'Theano==0.8.2'"
- "pip install -r requirements.txt"

install:
- "echo done"

# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage --cover-package=mcfly

after_script:
- "pip install scrutinizer-ocular"
- "ocular"
