language: python

python:
- "2.7"
- "3.2"  

before_install: 
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then       
    wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;       
  else
    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; 
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes 
- conda install -q pip openblas numpy scipy

- "pip install -q sphinx"
- "export PATH=$HOME/.local/bin:$PATH"
- sphinx-apidoc mcfly/ -o docs
- pwd
- cd docs
- make html
- pwd
- cd -
- pwd
- cd ..
- git config --global user.email "you@example.com"
- git config --global user.name "Your Name"
- git clone -b gh-pages https://$GH_TOKEN@github.com/NLeSC/mcfly.git pages
- cd -
- cd ../pages
- rm -rf *
- cp -r ../mcfly/docs/_build/html/* .
- git add .
- git commit -m "automatic doc update by travis-ci"
- git push
- cd -



- "pip install -q nose"
- "pip install 'coverage<4'"  # After 4, there is some issue when using python 3.2
- "pip install -qr requirements.txt"



install:
- "echo done"

# command to run tests, e.g. python setup.py test
script: 
- nosetests --with-coverage --cover-package=mcfly

after_script:
- "pip install scrutinizer-ocular"
- "ocular"
 
