language: python

python:
- "2.7"
- "3.2"  

before_install: 
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then       
    wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;       
  else
    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; 
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes 
- conda install -q pip openblas numpy
- "pip install -q nose"
- "pip install 'coverage<4'"  # After 4, there is some issue when using python 3.2
- "pip install -qr requirements.txt"
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then       
    pip install -qr requirements_python2specific.txt;
  else
    pip install -qr requirements_python3specific.txt;
  fi

install:
- "echo done"

# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage --cover-package=mcfly

after_script:
- "pip install scrutinizer-ocular"
- "ocular"
