language: python

python:
- "2.7"
- "3.2"  

before_install: 
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then       
    wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;       
  else
    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; 
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes 
- conda install -q pip openblas numpy scipy

- "pip install -q sphinx"
- "export PATH=$HOME/.local/bin:$PATH"
- pwd
- cd docs
- make html
- pwd
- cd -
- pwd
- cd ..
- git clone -b gh-pages https://github.com/NLeSC/mcfly.git
- cd -



- "pip install -q nose"
- "pip install 'coverage<4'"  # After 4, there is some issue when using python 3.2
- "pip install -qr requirements.txt"



install:
- "echo done"

# command to run tests, e.g. python setup.py test
script: 
- nosetests --with-coverage --cover-package=mcfly

after_script:
- "pip install scrutinizer-ocular"
- "ocular"
- sphinx-apidoc mcfly/ -o docs
 
