language: python

virtualenv:
  system_site_packages: true

python:
- "2.7"
- "3.2"  

before_install: 
- "sudo apt-get -qq install liblapack-dev python-numpy python-scipy python3-scipy python-sklearn gfortran"
- "pip install -q 'coverage>4' nose"
- "pip install -q 'scikit-learn>=0.15.0'"  # So less time can be spent building requirements and Travis-ci wont time out
- "pip install -qr requirements.txt"

install:
- "echo done"

# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage --cover-package=mcfly

after_script:
- "pip install scrutinizer-ocular"
- "ocular"
