name: mcfly
channels:
- conda-forge
- defaults
dependencies:
- python-dateutil
- keras
- protobuf
- tensorflow
- cycler
- freetype
- funcsigs
- functools32
- h5py
- hdf5
- icu
- libpng
- matplotlib
- mkl
- mock
- numpy
- openssl
- pandas
- pbr
- pip
- pyparsing
- pyqt
- python
- pytz
- pyyaml
- qt
- readline
- scikit-learn
- scipy
- setuptools
- sip
- six
- sqlite
- subprocess32
- theano
- tk
- wheel
- yaml
- zlib
